#!/usr/bin/env bash
set -euo pipefail

echo "=== DevAI Studio Railway Build ==="
echo "Node: $(node --version)"
echo "Bun: $(bun --version 2>/dev/null || echo 'not found (using npx)')"

# ── Generate .env from Railway environment variables ──────
# Expo/Metro needs EXPO_PUBLIC_* vars in the environment at
# bundle time. Railway injects them into the shell, but we
# also write a .env file so Metro's dotenv plugin picks them up.

ENV_FILE=".env"
echo "# Auto-generated by build-railway.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$ENV_FILE"

for var in $(env | grep '^EXPO_PUBLIC_' | cut -d= -f1); do
  echo "${var}=${!var}" >> "$ENV_FILE"
  echo "  → $var = ${!var:0:30}..."
done

# Also pass through any VITE_ or other public vars
for var in $(env | grep -E '^(VITE_|NEXT_PUBLIC_|REACT_APP_)' | cut -d= -f1); do
  echo "${var}=${!var}" >> "$ENV_FILE"
done

# Set NODE_ENV if not set
echo "NODE_ENV=${NODE_ENV:-production}" >> "$ENV_FILE"

count=$(grep -c '=' "$ENV_FILE" 2>/dev/null || echo 0)
echo "→ Wrote $count lines to .env"

# ── Install dependencies ─────────────────────────────────
echo ""
echo "=== Installing dependencies ==="
bun install --frozen-lockfile

# ── Export web build ─────────────────────────────────────
echo ""
echo "=== Building Expo web export ==="
npx expo export --platform web

# ── Verify output ────────────────────────────────────────
echo ""
echo "=== Build output ==="
if [ -f dist/index.html ]; then
  echo "✓ dist/index.html exists"
  echo "  Size: $(du -sh dist/ 2>/dev/null | cut -f1 || echo 'unknown')"
  echo "  Files: $(find dist/ -type f 2>/dev/null | wc -l || echo 0)"
else
  echo "✗ dist/index.html NOT FOUND — build may have failed"
  find . -name "index.html" -type f 2>/dev/null | head -10
  exit 1
fi

echo ""
echo "=== Build complete ==="
